### ISSUE TITLE
The toy-data link http://www.cse.yorku.ca/~mridataset/ is invalid. Would you please kindly update it?

### ISSUE THREAD

**Issue by chuan1093** [koflera/DynamicRadCineMRI#2]

**Comment by koflera** [comment]
Dear chuan1093,
the dataset is the same as the one that can be found here. 
http://jtl.lassonde.yorku.ca/software/datasets/
However, the corresponding download link on this website also seems not to work. Maybe it's a temporary problem?

Best regards,

Andreas

**Comment by koflera** [comment]
Dear chuan1093,

I just checked again the website after a while and it still does not seem to be working. Maybe the best thing is to directly contact the guys from the lab.

Best,
Andreas

**Comment by koflera** [comment]
Dear chuan1093,
the link for the cardiac dataset should be working again.
Best regards,
Andreas
